# Replace these with your actual keys
sonar.projectKey=Mohammadakhil_Sentinel-Auth-A-Production-Grade-3-Tier-DevSecOps-Ecosystem
sonar.organization=mahammadakhil
sonar.host.url=https://sonarcloud.io

# Path to the source code (this matches your 3-tier structure)
sonar.sources=app,frontend
sonar.sourceEncoding=UTF-8

# Optimization: Exclude noise to keep the report clean
sonar.exclusions=**/node_modules/**,**/venv/**,**/tests/**,frontend/build/**
sonar.python.version=3.11
